services:
  web:
    build: .
    container_name: skinflow_web

    env_file:
      - .env

    volumes:
      - .:/app

    ports:
      - "${DJANGO_PORT}:${DJANGO_PORT}"

    depends_on:
      - db

    command: sh scripts/run-verbose.sh

  db:
    image: postgres:17
    container_name: skinflow_db

    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: