# Generated by Django 5.2.15 on 2026-06-20 19:25

import django.db.models.deletion
import usermanagement.validators
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11, unique=True, validators=[usermanagement.validators.validate_iranian_phone], verbose_name='شماره موبایل')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='ایمیل')),
                ('role', models.CharField(choices=[('client', 'مراجعه\u200cکننده'), ('consultant', 'مشاور'), ('support', 'پشتیبان'), ('admin', 'مدیر')], default='client', max_length=20, verbose_name='نقش')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='آخرین ورود')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(default=list, verbose_name='دسترسی\u200cها')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل مدیر',
                'verbose_name_plural': 'پروفایل مدیران',
                'db_table': 'admin_profiles',
            },
        ),
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'مرد'), ('female', 'زن'), ('other', 'سایر')], max_length=10, null=True, verbose_name='جنسیت')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('timezone', models.CharField(default='Asia/Tehran', max_length=50, verbose_name='منطقه زمانی')),
                ('preferred_language', models.CharField(default='fa', max_length=10, verbose_name='زبان ترجیحی')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'client'}, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل مراجعه\u200cکننده',
                'verbose_name_plural': 'پروفایل مراجعه\u200cکنندگان',
                'db_table': 'client_profiles',
            },
        ),
        migrations.CreateModel(
            name='ConsultantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('specialties', models.JSONField(default=list, verbose_name='تخصص\u200cها')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره پروانه')),
                ('years_of_experience', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='سال\u200cهای تجربه')),
                ('is_available', models.BooleanField(default=True, verbose_name='در دسترس')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='میانگین امتیاز')),
                ('total_sessions', models.PositiveIntegerField(default=0, verbose_name='کل جلسات')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'consultant'}, on_delete=django.db.models.deletion.CASCADE, related_name='consultant_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل مشاور',
                'verbose_name_plural': 'پروفایل مشاوران',
                'db_table': 'consultant_profiles',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_enabled', models.BooleanField(default=True, verbose_name='پیامک')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='ایمیل')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='پوش نوتیفیکیشن')),
                ('appointment_reminder', models.BooleanField(default=True, verbose_name='یادآوری نوبت')),
                ('message_alerts', models.BooleanField(default=True, verbose_name='اعلان پیام')),
                ('order_updates', models.BooleanField(default=True, verbose_name='به\u200cروزرسانی سفارش')),
                ('progress_nudges', models.BooleanField(default=True, verbose_name='یادآوری پیشرفت درمان')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تنظیمات اعلان',
                'verbose_name_plural': 'تنظیمات اعلان\u200cها',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, verbose_name='کد')),
                ('purpose', models.CharField(choices=[('register', 'ثبت\u200cنام'), ('login', 'ورود'), ('reset_password', 'بازیابی رمز'), ('verify_email', 'تایید ایمیل')], max_length=20, verbose_name='هدف')),
                ('is_used', models.BooleanField(default=False, verbose_name='استفاده شده')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد تلاش')),
                ('expires_at', models.DateTimeField(verbose_name='انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPها',
                'db_table': 'otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پروفایل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'support'}, on_delete=django.db.models.deletion.CASCADE, related_name='support_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل پشتیبان',
                'verbose_name_plural': 'پروفایل پشتیبانان',
                'db_table': 'support_profiles',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True, verbose_name='برچسب')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('street', models.TextField(verbose_name='آدرس')),
                ('postal_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('is_default', models.BooleanField(default=False, verbose_name='پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس',
                'verbose_name_plural': 'آدرس\u200cها',
                'db_table': 'user_addresses',
            },
        ),
    ]
